// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tts.proto

package com.aiadver.api.tts.grpc;

public final class TtsOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsRequest_SessionParamEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsRequest_SessionParamEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsResult_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsResult_DataInfoEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsResult_DataInfoEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\ttts.proto\022\003tts\"\231\001\n\nTtsRequest\0227\n\014sessi" +
                        "onParam\030\001 \003(\0132!.tts.TtsRequest.SessionPa" +
                        "ramEntry\022\014\n\004text\030\002 \001(\t\022\017\n\007endFlag\030\003 \001(\010\032" +
                        "3\n\021SessionParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
                        "ue\030\002 \001(\t:\0028\001\"\254\001\n\tTtsResult\022\016\n\006errStr\030\001 \001" +
                        "(\t\022\017\n\007errCode\030\002 \001(\005\022\014\n\004data\030\003 \001(\014\022.\n\010dat" +
                        "aInfo\030\004 \003(\0132\034.tts.TtsResult.DataInfoEntr" +
                        "y\022\017\n\007endFlag\030\005 \001(\010\032/\n\rDataInfoEntry\022\013\n\003k" +
                        "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\00129\n\003Tts\0222\n\tcr" +
                        "eateRec\022\017.tts.TtsRequest\032\016.tts.TtsResult" +
                        "\"\000(\0010\001B\032\n\030com.aiadver.api.tts.grpcb\006prot" +
                        "o3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_tts_TtsRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tts_TtsRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsRequest_descriptor,
                new java.lang.String[]{"SessionParam", "Text", "EndFlag",});
        internal_static_tts_TtsRequest_SessionParamEntry_descriptor =
                internal_static_tts_TtsRequest_descriptor.getNestedTypes().get(0);
        internal_static_tts_TtsRequest_SessionParamEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsRequest_SessionParamEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_tts_TtsResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tts_TtsResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsResult_descriptor,
                new java.lang.String[]{"ErrStr", "ErrCode", "Data", "DataInfo", "EndFlag",});
        internal_static_tts_TtsResult_DataInfoEntry_descriptor =
                internal_static_tts_TtsResult_descriptor.getNestedTypes().get(0);
        internal_static_tts_TtsResult_DataInfoEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsResult_DataInfoEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
    }

    private TtsOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface TtsRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tts.TtsRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        int getSessionParamCount();

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        boolean containsSessionParam(
                java.lang.String key);

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getSessionParam();

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getSessionParamMap();

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        java.lang.String getSessionParamOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        java.lang.String getSessionParamOrThrow(
                java.lang.String key);

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         *
         * @return The text.
         */
        java.lang.String getText();

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         *
         * @return The bytes for text.
         */
        com.google.protobuf.ByteString
        getTextBytes();

        /**
         * <pre>
         * 最后一次文本标志符
         * </pre>
         *
         * <code>bool endFlag = 3;</code>
         *
         * @return The endFlag.
         */
        boolean getEndFlag();
    }

    public interface TtsResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tts.TtsResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The errStr.
         */
        java.lang.String getErrStr();

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The bytes for errStr.
         */
        com.google.protobuf.ByteString
        getErrStrBytes();

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         *
         * @return The errCode.
         */
        int getErrCode();

        /**
         * <pre>
         * 返回的音频数据（没有音频头）
         * </pre>
         *
         * <code>bytes data = 3;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        int getDataInfoCount();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        boolean containsDataInfo(
                java.lang.String key);

        /**
         * Use {@link #getDataInfoMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getDataInfo();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getDataInfoMap();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        java.lang.String getDataInfoOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        java.lang.String getDataInfoOrThrow(
                java.lang.String key);

        /**
         * <pre>
         * 最后一次音频标识符
         * </pre>
         *
         * <code>bool endFlag = 5;</code>
         *
         * @return The endFlag.
         */
        boolean getEndFlag();
    }

    /**
     * Protobuf type {@code tts.TtsRequest}
     */
    public static final class TtsRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tts.TtsRequest)
            TtsRequestOrBuilder {
        public static final int SESSIONPARAM_FIELD_NUMBER = 1;
        public static final int TEXT_FIELD_NUMBER = 2;
        public static final int ENDFLAG_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:tts.TtsRequest)
        private static final com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<TtsRequest>
                PARSER = new com.google.protobuf.AbstractParser<TtsRequest>() {
            @java.lang.Override
            public TtsRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TtsRequest(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest();
        }

        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> sessionParam_;
        private volatile java.lang.Object text_;
        private boolean endFlag_;
        private byte memoizedIsInitialized = -1;

        // Use TtsRequest.newBuilder() to construct.
        private TtsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TtsRequest() {
            text_ = "";
        }

        private TtsRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                sessionParam_ = com.google.protobuf.MapField.newMapField(
                                        SessionParamDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    sessionParam__ = input.readMessage(
                                    SessionParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            sessionParam_.getMutableMap().put(
                                    sessionParam__.getKey(), sessionParam__.getValue());
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            text_ = s;
                            break;
                        }
                        case 24: {

                            endFlag_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsRequest_descriptor;
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<TtsRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new TtsRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetSessionParam();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.class, com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.Builder.class);
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetSessionParam() {
            if (sessionParam_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        SessionParamDefaultEntryHolder.defaultEntry);
            }
            return sessionParam_;
        }

        public int getSessionParamCount() {
            return internalGetSessionParam().getMap().size();
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        @java.lang.Override
        public boolean containsSessionParam(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetSessionParam().getMap().containsKey(key);
        }

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getSessionParam() {
            return getSessionParamMap();
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, java.lang.String> getSessionParamMap() {
            return internalGetSessionParam().getMap();
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        @java.lang.Override

        public java.lang.String getSessionParamOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetSessionParam().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        @java.lang.Override

        public java.lang.String getSessionParamOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetSessionParam().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         *
         * @return The text.
         */
        @java.lang.Override
        public java.lang.String getText() {
            java.lang.Object ref = text_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         *
         * @return The bytes for text.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getTextBytes() {
            java.lang.Object ref = text_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 最后一次文本标志符
         * </pre>
         *
         * <code>bool endFlag = 3;</code>
         *
         * @return The endFlag.
         */
        @java.lang.Override
        public boolean getEndFlag() {
            return endFlag_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetSessionParam(),
                            SessionParamDefaultEntryHolder.defaultEntry,
                            1);
            if (!getTextBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
            }
            if (endFlag_ != false) {
                output.writeBool(3, endFlag_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetSessionParam().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        sessionParam__ = SessionParamDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, sessionParam__);
            }
            if (!getTextBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, endFlag_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest)) {
                return super.equals(obj);
            }
            com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest other = (com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest) obj;

            if (!internalGetSessionParam().equals(
                    other.internalGetSessionParam())) return false;
            if (!getText()
                    .equals(other.getText())) return false;
            if (getEndFlag()
                    != other.getEndFlag()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetSessionParam().getMap().isEmpty()) {
                hash = (37 * hash) + SESSIONPARAM_FIELD_NUMBER;
                hash = (53 * hash) + internalGetSessionParam().hashCode();
            }
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TtsRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class SessionParamDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsRequest_SessionParamEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        /**
         * Protobuf type {@code tts.TtsRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tts.TtsRequest)
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequestOrBuilder {
            private int bitField0_;
            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> sessionParam_;
            private java.lang.Object text_ = "";
            private boolean endFlag_;

            // Construct using com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsRequest_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.class, com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                internalGetMutableSessionParam().clear();
                text_ = "";

                endFlag_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsRequest_descriptor;
            }

            @java.lang.Override
            public com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest getDefaultInstanceForType() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.getDefaultInstance();
            }

            @java.lang.Override
            public com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest build() {
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest buildPartial() {
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest result = new com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest(this);
                int from_bitField0_ = bitField0_;
                result.sessionParam_ = internalGetSessionParam();
                result.sessionParam_.makeImmutable();
                result.text_ = text_;
                result.endFlag_ = endFlag_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest) {
                    return mergeFrom((com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest other) {
                if (other == com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest.getDefaultInstance()) return this;
                internalGetMutableSessionParam().mergeFrom(
                        other.internalGetSessionParam());
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    onChanged();
                }
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.aiadver.api.tts.grpc.TtsOuterClass.TtsRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetSessionParam() {
                if (sessionParam_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                return sessionParam_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableSessionParam() {
                onChanged();
                ;
                if (sessionParam_ == null) {
                    sessionParam_ = com.google.protobuf.MapField.newMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                if (!sessionParam_.isMutable()) {
                    sessionParam_ = sessionParam_.copy();
                }
                return sessionParam_;
            }

            public int getSessionParamCount() {
                return internalGetSessionParam().getMap().size();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            @java.lang.Override
            public boolean containsSessionParam(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetSessionParam().getMap().containsKey(key);
            }

            /**
             * Use {@link #getSessionParamMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getSessionParam() {
                return getSessionParamMap();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            @java.lang.Override

            public java.util.Map<java.lang.String, java.lang.String> getSessionParamMap() {
                return internalGetSessionParam().getMap();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            @java.lang.Override

            public java.lang.String getSessionParamOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetSessionParam().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            @java.lang.Override

            public java.lang.String getSessionParamOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetSessionParam().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearSessionParam() {
                internalGetMutableSessionParam().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder removeSessionParam(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableSessionParam() {
                return internalGetMutableSessionParam().getMutableMap();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            public Builder putSessionParam(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder putAllSessionParam(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableSessionParam().getMutableMap()
                        .putAll(values);
                return this;
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             *
             * @return The text.
             */
            public java.lang.String getText() {
                java.lang.Object ref = text_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             *
             * @param value The text to set.
             * @return This builder for chaining.
             */
            public Builder setText(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                text_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             *
             * @return The bytes for text.
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                java.lang.Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             *
             * @param value The bytes for text to set.
             * @return This builder for chaining.
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                text_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearText() {

                text_ = getDefaultInstance().getText();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 最后一次文本标志符
             * </pre>
             *
             * <code>bool endFlag = 3;</code>
             *
             * @return The endFlag.
             */
            @java.lang.Override
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 最后一次文本标志符
             * </pre>
             *
             * <code>bool endFlag = 3;</code>
             *
             * @param value The endFlag to set.
             * @return This builder for chaining.
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 最后一次文本标志符
             * </pre>
             *
             * <code>bool endFlag = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tts.TtsRequest)
        }

    }

    /**
     * Protobuf type {@code tts.TtsResult}
     */
    public static final class TtsResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tts.TtsResult)
            TtsResultOrBuilder {
        public static final int ERRSTR_FIELD_NUMBER = 1;
        public static final int ERRCODE_FIELD_NUMBER = 2;
        public static final int DATA_FIELD_NUMBER = 3;
        public static final int DATAINFO_FIELD_NUMBER = 4;
        public static final int ENDFLAG_FIELD_NUMBER = 5;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:tts.TtsResult)
        private static final com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<TtsResult>
                PARSER = new com.google.protobuf.AbstractParser<TtsResult>() {
            @java.lang.Override
            public TtsResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TtsResult(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult();
        }

        private volatile java.lang.Object errStr_;
        private int errCode_;
        private com.google.protobuf.ByteString data_;
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> dataInfo_;
        private boolean endFlag_;
        private byte memoizedIsInitialized = -1;

        // Use TtsResult.newBuilder() to construct.
        private TtsResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TtsResult() {
            errStr_ = "";
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        private TtsResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            errStr_ = s;
                            break;
                        }
                        case 16: {

                            errCode_ = input.readInt32();
                            break;
                        }
                        case 26: {

                            data_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                dataInfo_ = com.google.protobuf.MapField.newMapField(
                                        DataInfoDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    dataInfo__ = input.readMessage(
                                    DataInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            dataInfo_.getMutableMap().put(
                                    dataInfo__.getKey(), dataInfo__.getValue());
                            break;
                        }
                        case 40: {

                            endFlag_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsResult_descriptor;
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<TtsResult> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new TtsResult();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetDataInfo();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.class, com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.Builder.class);
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The errStr.
         */
        @java.lang.Override
        public java.lang.String getErrStr() {
            java.lang.Object ref = errStr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                errStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The bytes for errStr.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getErrStrBytes() {
            java.lang.Object ref = errStr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         *
         * @return The errCode.
         */
        @java.lang.Override
        public int getErrCode() {
            return errCode_;
        }

        /**
         * <pre>
         * 返回的音频数据（没有音频头）
         * </pre>
         *
         * <code>bytes data = 3;</code>
         *
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetDataInfo() {
            if (dataInfo_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        DataInfoDefaultEntryHolder.defaultEntry);
            }
            return dataInfo_;
        }

        public int getDataInfoCount() {
            return internalGetDataInfo().getMap().size();
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        @java.lang.Override
        public boolean containsDataInfo(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetDataInfo().getMap().containsKey(key);
        }

        /**
         * Use {@link #getDataInfoMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getDataInfo() {
            return getDataInfoMap();
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, java.lang.String> getDataInfoMap() {
            return internalGetDataInfo().getMap();
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        @java.lang.Override

        public java.lang.String getDataInfoOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetDataInfo().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        @java.lang.Override

        public java.lang.String getDataInfoOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetDataInfo().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        /**
         * <pre>
         * 最后一次音频标识符
         * </pre>
         *
         * <code>bool endFlag = 5;</code>
         *
         * @return The endFlag.
         */
        @java.lang.Override
        public boolean getEndFlag() {
            return endFlag_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getErrStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errStr_);
            }
            if (errCode_ != 0) {
                output.writeInt32(2, errCode_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(3, data_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetDataInfo(),
                            DataInfoDefaultEntryHolder.defaultEntry,
                            4);
            if (endFlag_ != false) {
                output.writeBool(5, endFlag_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getErrStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errStr_);
            }
            if (errCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, errCode_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, data_);
            }
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetDataInfo().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        dataInfo__ = DataInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, dataInfo__);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, endFlag_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult)) {
                return super.equals(obj);
            }
            com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult other = (com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult) obj;

            if (!getErrStr()
                    .equals(other.getErrStr())) return false;
            if (getErrCode()
                    != other.getErrCode()) return false;
            if (!getData()
                    .equals(other.getData())) return false;
            if (!internalGetDataInfo().equals(
                    other.internalGetDataInfo())) return false;
            if (getEndFlag()
                    != other.getEndFlag()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
            hash = (53 * hash) + getErrStr().hashCode();
            hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            if (!internalGetDataInfo().getMap().isEmpty()) {
                hash = (37 * hash) + DATAINFO_FIELD_NUMBER;
                hash = (53 * hash) + internalGetDataInfo().hashCode();
            }
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TtsResult> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class DataInfoDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsResult_DataInfoEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        /**
         * Protobuf type {@code tts.TtsResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tts.TtsResult)
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsResultOrBuilder {
            private int bitField0_;
            private java.lang.Object errStr_ = "";
            private int errCode_;
            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> dataInfo_;
            private boolean endFlag_;

            // Construct using com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsResult_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetDataInfo();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableDataInfo();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.class, com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                errStr_ = "";

                errCode_ = 0;

                data_ = com.google.protobuf.ByteString.EMPTY;

                internalGetMutableDataInfo().clear();
                endFlag_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.internal_static_tts_TtsResult_descriptor;
            }

            @java.lang.Override
            public com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult getDefaultInstanceForType() {
                return com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.getDefaultInstance();
            }

            @java.lang.Override
            public com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult build() {
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult buildPartial() {
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult result = new com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult(this);
                int from_bitField0_ = bitField0_;
                result.errStr_ = errStr_;
                result.errCode_ = errCode_;
                result.data_ = data_;
                result.dataInfo_ = internalGetDataInfo();
                result.dataInfo_.makeImmutable();
                result.endFlag_ = endFlag_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult) {
                    return mergeFrom((com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult other) {
                if (other == com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult.getDefaultInstance()) return this;
                if (!other.getErrStr().isEmpty()) {
                    errStr_ = other.errStr_;
                    onChanged();
                }
                if (other.getErrCode() != 0) {
                    setErrCode(other.getErrCode());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                internalGetMutableDataInfo().mergeFrom(
                        other.internalGetDataInfo());
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.aiadver.api.tts.grpc.TtsOuterClass.TtsResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @return The errStr.
             */
            public java.lang.String getErrStr() {
                java.lang.Object ref = errStr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    errStr_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @param value The errStr to set.
             * @return This builder for chaining.
             */
            public Builder setErrStr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @return The bytes for errStr.
             */
            public com.google.protobuf.ByteString
            getErrStrBytes() {
                java.lang.Object ref = errStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    errStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @param value The bytes for errStr to set.
             * @return This builder for chaining.
             */
            public Builder setErrStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearErrStr() {

                errStr_ = getDefaultInstance().getErrStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             *
             * @return The errCode.
             */
            @java.lang.Override
            public int getErrCode() {
                return errCode_;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             *
             * @param value The errCode to set.
             * @return This builder for chaining.
             */
            public Builder setErrCode(int value) {

                errCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearErrCode() {

                errCode_ = 0;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的音频数据（没有音频头）
             * </pre>
             *
             * <code>bytes data = 3;</code>
             *
             * @return The data.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <pre>
             * 返回的音频数据（没有音频头）
             * </pre>
             *
             * <code>bytes data = 3;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的音频数据（没有音频头）
             * </pre>
             *
             * <code>bytes data = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetDataInfo() {
                if (dataInfo_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            DataInfoDefaultEntryHolder.defaultEntry);
                }
                return dataInfo_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableDataInfo() {
                onChanged();
                ;
                if (dataInfo_ == null) {
                    dataInfo_ = com.google.protobuf.MapField.newMapField(
                            DataInfoDefaultEntryHolder.defaultEntry);
                }
                if (!dataInfo_.isMutable()) {
                    dataInfo_ = dataInfo_.copy();
                }
                return dataInfo_;
            }

            public int getDataInfoCount() {
                return internalGetDataInfo().getMap().size();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            @java.lang.Override
            public boolean containsDataInfo(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetDataInfo().getMap().containsKey(key);
            }

            /**
             * Use {@link #getDataInfoMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getDataInfo() {
                return getDataInfoMap();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */
            @java.lang.Override

            public java.util.Map<java.lang.String, java.lang.String> getDataInfoMap() {
                return internalGetDataInfo().getMap();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */
            @java.lang.Override

            public java.lang.String getDataInfoOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetDataInfo().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */
            @java.lang.Override

            public java.lang.String getDataInfoOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetDataInfo().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearDataInfo() {
                internalGetMutableDataInfo().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public Builder removeDataInfo(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableDataInfo().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableDataInfo() {
                return internalGetMutableDataInfo().getMutableMap();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */
            public Builder putDataInfo(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableDataInfo().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public Builder putAllDataInfo(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableDataInfo().getMutableMap()
                        .putAll(values);
                return this;
            }

            /**
             * <pre>
             * 最后一次音频标识符
             * </pre>
             *
             * <code>bool endFlag = 5;</code>
             *
             * @return The endFlag.
             */
            @java.lang.Override
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 最后一次音频标识符
             * </pre>
             *
             * <code>bool endFlag = 5;</code>
             *
             * @param value The endFlag to set.
             * @return This builder for chaining.
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 最后一次音频标识符
             * </pre>
             *
             * <code>bool endFlag = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tts.TtsResult)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
