spring:
  application:
    name: aiadver-microservice-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8084/oauth/jwt/jwkSet
server:
  port: 8080