// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asr.proto

package com.aiadver.api.asr.grpc;

public final class Asr {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_iat_IatRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_iat_IatRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_iat_IatRequest_SessionParamEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_iat_IatRequest_SessionParamEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_iat_IatResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_iat_IatResult_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tasr.proto\022\003iat\032\034google/api/annotations" +
                        ".proto\"\261\001\n\nIatRequest\0227\n\014sessionParam\030\001 " +
                        "\003(\0132!.iat.IatRequest.SessionParamEntry\022\017" +
                        "\n\007samples\030\002 \001(\014\022\023\n\013samplesInfo\030\003 \001(\t\022\017\n\007" +
                        "endFlag\030\004 \001(\010\0323\n\021SessionParamEntry\022\013\n\003ke" +
                        "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"M\n\tIatResult\022" +
                        "\016\n\006errStr\030\001 \001(\t\022\017\n\007errCode\030\002 \001(\005\022\016\n\006ansS" +
                        "tr\030\003 \001(\t\022\017\n\007endFlag\030\004 \001(\0102N\n\003Iat\022G\n\tcrea" +
                        "teRec\022\017.iat.IatRequest\032\016.iat.IatResult\"\025" +
                        "\202\323\344\223\002\017\"\n/createRec:\001*(\0010\001B\032\n\030com.aiadver" +
                        ".api.asr.grpcb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.api.AnnotationsProto.getDescriptor(),
                        });
        internal_static_iat_IatRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_iat_IatRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_iat_IatRequest_descriptor,
                new java.lang.String[]{"SessionParam", "Samples", "SamplesInfo", "EndFlag",});
        internal_static_iat_IatRequest_SessionParamEntry_descriptor =
                internal_static_iat_IatRequest_descriptor.getNestedTypes().get(0);
        internal_static_iat_IatRequest_SessionParamEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_iat_IatRequest_SessionParamEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_iat_IatResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_iat_IatResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_iat_IatResult_descriptor,
                new java.lang.String[]{"ErrStr", "ErrCode", "AnsStr", "EndFlag",});
        com.google.protobuf.ExtensionRegistry registry =
                com.google.protobuf.ExtensionRegistry.newInstance();
        registry.add(com.google.api.AnnotationsProto.http);
        com.google.protobuf.Descriptors.FileDescriptor
                .internalUpdateFileDescriptor(descriptor, registry);
        com.google.api.AnnotationsProto.getDescriptor();
    }

    private Asr() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface IatRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:iat.IatRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        int getSessionParamCount();

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        boolean containsSessionParam(
                java.lang.String key);

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getSessionParam();

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getSessionParamMap();

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        java.lang.String getSessionParamOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        java.lang.String getSessionParamOrThrow(
                java.lang.String key);

        /**
         * <pre>
         * 音频数据
         * </pre>
         *
         * <code>bytes samples = 2;</code>
         *
         * @return The samples.
         */
        com.google.protobuf.ByteString getSamples();

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         *
         * @return The samplesInfo.
         */
        java.lang.String getSamplesInfo();

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         *
         * @return The bytes for samplesInfo.
         */
        com.google.protobuf.ByteString
        getSamplesInfoBytes();

        /**
         * <pre>
         * 音频结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         *
         * @return The endFlag.
         */
        boolean getEndFlag();
    }

    public interface IatResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:iat.IatResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The errStr.
         */
        java.lang.String getErrStr();

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The bytes for errStr.
         */
        com.google.protobuf.ByteString
        getErrStrBytes();

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         *
         * @return The errCode.
         */
        int getErrCode();

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         *
         * @return The ansStr.
         */
        java.lang.String getAnsStr();

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         *
         * @return The bytes for ansStr.
         */
        com.google.protobuf.ByteString
        getAnsStrBytes();

        /**
         * <pre>
         * 识别结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         *
         * @return The endFlag.
         */
        boolean getEndFlag();
    }

    /**
     * <pre>
     * 请求参数
     * </pre>
     * <p>
     * Protobuf type {@code iat.IatRequest}
     */
    public static final class IatRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:iat.IatRequest)
            IatRequestOrBuilder {
        public static final int SESSIONPARAM_FIELD_NUMBER = 1;
        public static final int SAMPLES_FIELD_NUMBER = 2;
        public static final int SAMPLESINFO_FIELD_NUMBER = 3;
        public static final int ENDFLAG_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:iat.IatRequest)
        private static final com.aiadver.api.asr.grpc.Asr.IatRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<IatRequest>
                PARSER = new com.google.protobuf.AbstractParser<IatRequest>() {
            @java.lang.Override
            public IatRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new IatRequest(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.aiadver.api.asr.grpc.Asr.IatRequest();
        }

        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> sessionParam_;
        private com.google.protobuf.ByteString samples_;
        private volatile java.lang.Object samplesInfo_;
        private boolean endFlag_;
        private byte memoizedIsInitialized = -1;

        // Use IatRequest.newBuilder() to construct.
        private IatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private IatRequest() {
            samples_ = com.google.protobuf.ByteString.EMPTY;
            samplesInfo_ = "";
        }

        private IatRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                sessionParam_ = com.google.protobuf.MapField.newMapField(
                                        SessionParamDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    sessionParam__ = input.readMessage(
                                    SessionParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            sessionParam_.getMutableMap().put(
                                    sessionParam__.getKey(), sessionParam__.getValue());
                            break;
                        }
                        case 18: {

                            samples_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            samplesInfo_ = s;
                            break;
                        }
                        case 32: {

                            endFlag_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatRequest_descriptor;
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.aiadver.api.asr.grpc.Asr.IatRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<IatRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new IatRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetSessionParam();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.aiadver.api.asr.grpc.Asr.IatRequest.class, com.aiadver.api.asr.grpc.Asr.IatRequest.Builder.class);
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetSessionParam() {
            if (sessionParam_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        SessionParamDefaultEntryHolder.defaultEntry);
            }
            return sessionParam_;
        }

        public int getSessionParamCount() {
            return internalGetSessionParam().getMap().size();
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        @java.lang.Override
        public boolean containsSessionParam(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetSessionParam().getMap().containsKey(key);
        }

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getSessionParam() {
            return getSessionParamMap();
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, java.lang.String> getSessionParamMap() {
            return internalGetSessionParam().getMap();
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        @java.lang.Override

        public java.lang.String getSessionParamOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetSessionParam().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        @java.lang.Override

        public java.lang.String getSessionParamOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetSessionParam().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        /**
         * <pre>
         * 音频数据
         * </pre>
         *
         * <code>bytes samples = 2;</code>
         *
         * @return The samples.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getSamples() {
            return samples_;
        }

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         *
         * @return The samplesInfo.
         */
        @java.lang.Override
        public java.lang.String getSamplesInfo() {
            java.lang.Object ref = samplesInfo_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                samplesInfo_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 音频数据信息，扩展参数，保留
         * </pre>
         *
         * <code>string samplesInfo = 3;</code>
         *
         * @return The bytes for samplesInfo.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSamplesInfoBytes() {
            java.lang.Object ref = samplesInfo_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                samplesInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 音频结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         *
         * @return The endFlag.
         */
        @java.lang.Override
        public boolean getEndFlag() {
            return endFlag_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetSessionParam(),
                            SessionParamDefaultEntryHolder.defaultEntry,
                            1);
            if (!samples_.isEmpty()) {
                output.writeBytes(2, samples_);
            }
            if (!getSamplesInfoBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, samplesInfo_);
            }
            if (endFlag_ != false) {
                output.writeBool(4, endFlag_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetSessionParam().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        sessionParam__ = SessionParamDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, sessionParam__);
            }
            if (!samples_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, samples_);
            }
            if (!getSamplesInfoBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, samplesInfo_);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, endFlag_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.aiadver.api.asr.grpc.Asr.IatRequest)) {
                return super.equals(obj);
            }
            com.aiadver.api.asr.grpc.Asr.IatRequest other = (com.aiadver.api.asr.grpc.Asr.IatRequest) obj;

            if (!internalGetSessionParam().equals(
                    other.internalGetSessionParam())) return false;
            if (!getSamples()
                    .equals(other.getSamples())) return false;
            if (!getSamplesInfo()
                    .equals(other.getSamplesInfo())) return false;
            if (getEndFlag()
                    != other.getEndFlag()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetSessionParam().getMap().isEmpty()) {
                hash = (37 * hash) + SESSIONPARAM_FIELD_NUMBER;
                hash = (53 * hash) + internalGetSessionParam().hashCode();
            }
            hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
            hash = (53 * hash) + getSamples().hashCode();
            hash = (37 * hash) + SAMPLESINFO_FIELD_NUMBER;
            hash = (53 * hash) + getSamplesInfo().hashCode();
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<IatRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.aiadver.api.asr.grpc.Asr.IatRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class SessionParamDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatRequest_SessionParamEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        /**
         * <pre>
         * 请求参数
         * </pre>
         * <p>
         * Protobuf type {@code iat.IatRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:iat.IatRequest)
                com.aiadver.api.asr.grpc.Asr.IatRequestOrBuilder {
            private int bitField0_;
            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> sessionParam_;
            private com.google.protobuf.ByteString samples_ = com.google.protobuf.ByteString.EMPTY;
            private java.lang.Object samplesInfo_ = "";
            private boolean endFlag_;

            // Construct using com.aiadver.api.asr.grpc.Asr.IatRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatRequest_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.aiadver.api.asr.grpc.Asr.IatRequest.class, com.aiadver.api.asr.grpc.Asr.IatRequest.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                internalGetMutableSessionParam().clear();
                samples_ = com.google.protobuf.ByteString.EMPTY;

                samplesInfo_ = "";

                endFlag_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatRequest_descriptor;
            }

            @java.lang.Override
            public com.aiadver.api.asr.grpc.Asr.IatRequest getDefaultInstanceForType() {
                return com.aiadver.api.asr.grpc.Asr.IatRequest.getDefaultInstance();
            }

            @java.lang.Override
            public com.aiadver.api.asr.grpc.Asr.IatRequest build() {
                com.aiadver.api.asr.grpc.Asr.IatRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.aiadver.api.asr.grpc.Asr.IatRequest buildPartial() {
                com.aiadver.api.asr.grpc.Asr.IatRequest result = new com.aiadver.api.asr.grpc.Asr.IatRequest(this);
                int from_bitField0_ = bitField0_;
                result.sessionParam_ = internalGetSessionParam();
                result.sessionParam_.makeImmutable();
                result.samples_ = samples_;
                result.samplesInfo_ = samplesInfo_;
                result.endFlag_ = endFlag_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.aiadver.api.asr.grpc.Asr.IatRequest) {
                    return mergeFrom((com.aiadver.api.asr.grpc.Asr.IatRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.aiadver.api.asr.grpc.Asr.IatRequest other) {
                if (other == com.aiadver.api.asr.grpc.Asr.IatRequest.getDefaultInstance()) return this;
                internalGetMutableSessionParam().mergeFrom(
                        other.internalGetSessionParam());
                if (other.getSamples() != com.google.protobuf.ByteString.EMPTY) {
                    setSamples(other.getSamples());
                }
                if (!other.getSamplesInfo().isEmpty()) {
                    samplesInfo_ = other.samplesInfo_;
                    onChanged();
                }
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.aiadver.api.asr.grpc.Asr.IatRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.aiadver.api.asr.grpc.Asr.IatRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetSessionParam() {
                if (sessionParam_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                return sessionParam_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableSessionParam() {
                onChanged();
                ;
                if (sessionParam_ == null) {
                    sessionParam_ = com.google.protobuf.MapField.newMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                if (!sessionParam_.isMutable()) {
                    sessionParam_ = sessionParam_.copy();
                }
                return sessionParam_;
            }

            public int getSessionParamCount() {
                return internalGetSessionParam().getMap().size();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            @java.lang.Override
            public boolean containsSessionParam(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetSessionParam().getMap().containsKey(key);
            }

            /**
             * Use {@link #getSessionParamMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getSessionParam() {
                return getSessionParamMap();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            @java.lang.Override

            public java.util.Map<java.lang.String, java.lang.String> getSessionParamMap() {
                return internalGetSessionParam().getMap();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            @java.lang.Override

            public java.lang.String getSessionParamOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetSessionParam().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            @java.lang.Override

            public java.lang.String getSessionParamOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetSessionParam().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearSessionParam() {
                internalGetMutableSessionParam().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder removeSessionParam(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableSessionParam() {
                return internalGetMutableSessionParam().getMutableMap();
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            public Builder putSessionParam(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 创建会话参数，只要求传一次，后续持续向服务端写音频时可以忽略（服务也不再解析）,详细说明见：sessionParam参数说明
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder putAllSessionParam(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableSessionParam().getMutableMap()
                        .putAll(values);
                return this;
            }

            /**
             * <pre>
             * 音频数据
             * </pre>
             *
             * <code>bytes samples = 2;</code>
             *
             * @return The samples.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getSamples() {
                return samples_;
            }

            /**
             * <pre>
             * 音频数据
             * </pre>
             *
             * <code>bytes samples = 2;</code>
             *
             * @param value The samples to set.
             * @return This builder for chaining.
             */
            public Builder setSamples(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                samples_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据
             * </pre>
             *
             * <code>bytes samples = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSamples() {

                samples_ = getDefaultInstance().getSamples();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             *
             * @return The samplesInfo.
             */
            public java.lang.String getSamplesInfo() {
                java.lang.Object ref = samplesInfo_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    samplesInfo_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             *
             * @param value The samplesInfo to set.
             * @return This builder for chaining.
             */
            public Builder setSamplesInfo(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                samplesInfo_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             *
             * @return The bytes for samplesInfo.
             */
            public com.google.protobuf.ByteString
            getSamplesInfoBytes() {
                java.lang.Object ref = samplesInfo_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    samplesInfo_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             *
             * @param value The bytes for samplesInfo to set.
             * @return This builder for chaining.
             */
            public Builder setSamplesInfoBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                samplesInfo_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频数据信息，扩展参数，保留
             * </pre>
             *
             * <code>string samplesInfo = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSamplesInfo() {

                samplesInfo_ = getDefaultInstance().getSamplesInfo();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             *
             * @return The endFlag.
             */
            @java.lang.Override
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 音频结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             *
             * @param value The endFlag to set.
             * @return This builder for chaining.
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 音频结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:iat.IatRequest)
        }

    }

    /**
     * <pre>
     * 识别结果
     * </pre>
     * <p>
     * Protobuf type {@code iat.IatResult}
     */
    public static final class IatResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:iat.IatResult)
            IatResultOrBuilder {
        public static final int ERRSTR_FIELD_NUMBER = 1;
        public static final int ERRCODE_FIELD_NUMBER = 2;
        public static final int ANSSTR_FIELD_NUMBER = 3;
        public static final int ENDFLAG_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:iat.IatResult)
        private static final com.aiadver.api.asr.grpc.Asr.IatResult DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<IatResult>
                PARSER = new com.google.protobuf.AbstractParser<IatResult>() {
            @java.lang.Override
            public IatResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new IatResult(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.aiadver.api.asr.grpc.Asr.IatResult();
        }

        private volatile java.lang.Object errStr_;
        private int errCode_;
        private volatile java.lang.Object ansStr_;
        private boolean endFlag_;
        private byte memoizedIsInitialized = -1;

        // Use IatResult.newBuilder() to construct.
        private IatResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private IatResult() {
            errStr_ = "";
            ansStr_ = "";
        }

        private IatResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            errStr_ = s;
                            break;
                        }
                        case 16: {

                            errCode_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ansStr_ = s;
                            break;
                        }
                        case 32: {

                            endFlag_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatResult_descriptor;
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.aiadver.api.asr.grpc.Asr.IatResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.aiadver.api.asr.grpc.Asr.IatResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<IatResult> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new IatResult();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.aiadver.api.asr.grpc.Asr.IatResult.class, com.aiadver.api.asr.grpc.Asr.IatResult.Builder.class);
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The errStr.
         */
        @java.lang.Override
        public java.lang.String getErrStr() {
            java.lang.Object ref = errStr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                errStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         *
         * @return The bytes for errStr.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getErrStrBytes() {
            java.lang.Object ref = errStr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         *
         * @return The errCode.
         */
        @java.lang.Override
        public int getErrCode() {
            return errCode_;
        }

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         *
         * @return The ansStr.
         */
        @java.lang.Override
        public java.lang.String getAnsStr() {
            java.lang.Object ref = ansStr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ansStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 结果
         * </pre>
         *
         * <code>string ansStr = 3;</code>
         *
         * @return The bytes for ansStr.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getAnsStrBytes() {
            java.lang.Object ref = ansStr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ansStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 识别结束标记
         * </pre>
         *
         * <code>bool endFlag = 4;</code>
         *
         * @return The endFlag.
         */
        @java.lang.Override
        public boolean getEndFlag() {
            return endFlag_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getErrStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errStr_);
            }
            if (errCode_ != 0) {
                output.writeInt32(2, errCode_);
            }
            if (!getAnsStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ansStr_);
            }
            if (endFlag_ != false) {
                output.writeBool(4, endFlag_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getErrStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errStr_);
            }
            if (errCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, errCode_);
            }
            if (!getAnsStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ansStr_);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, endFlag_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.aiadver.api.asr.grpc.Asr.IatResult)) {
                return super.equals(obj);
            }
            com.aiadver.api.asr.grpc.Asr.IatResult other = (com.aiadver.api.asr.grpc.Asr.IatResult) obj;

            if (!getErrStr()
                    .equals(other.getErrStr())) return false;
            if (getErrCode()
                    != other.getErrCode()) return false;
            if (!getAnsStr()
                    .equals(other.getAnsStr())) return false;
            if (getEndFlag()
                    != other.getEndFlag()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
            hash = (53 * hash) + getErrStr().hashCode();
            hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrCode();
            hash = (37 * hash) + ANSSTR_FIELD_NUMBER;
            hash = (53 * hash) + getAnsStr().hashCode();
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<IatResult> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.aiadver.api.asr.grpc.Asr.IatResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * <pre>
         * 识别结果
         * </pre>
         * <p>
         * Protobuf type {@code iat.IatResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:iat.IatResult)
                com.aiadver.api.asr.grpc.Asr.IatResultOrBuilder {
            private java.lang.Object errStr_ = "";
            private int errCode_;
            private java.lang.Object ansStr_ = "";
            private boolean endFlag_;

            // Construct using com.aiadver.api.asr.grpc.Asr.IatResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatResult_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.aiadver.api.asr.grpc.Asr.IatResult.class, com.aiadver.api.asr.grpc.Asr.IatResult.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                errStr_ = "";

                errCode_ = 0;

                ansStr_ = "";

                endFlag_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.aiadver.api.asr.grpc.Asr.internal_static_iat_IatResult_descriptor;
            }

            @java.lang.Override
            public com.aiadver.api.asr.grpc.Asr.IatResult getDefaultInstanceForType() {
                return com.aiadver.api.asr.grpc.Asr.IatResult.getDefaultInstance();
            }

            @java.lang.Override
            public com.aiadver.api.asr.grpc.Asr.IatResult build() {
                com.aiadver.api.asr.grpc.Asr.IatResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.aiadver.api.asr.grpc.Asr.IatResult buildPartial() {
                com.aiadver.api.asr.grpc.Asr.IatResult result = new com.aiadver.api.asr.grpc.Asr.IatResult(this);
                result.errStr_ = errStr_;
                result.errCode_ = errCode_;
                result.ansStr_ = ansStr_;
                result.endFlag_ = endFlag_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.aiadver.api.asr.grpc.Asr.IatResult) {
                    return mergeFrom((com.aiadver.api.asr.grpc.Asr.IatResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.aiadver.api.asr.grpc.Asr.IatResult other) {
                if (other == com.aiadver.api.asr.grpc.Asr.IatResult.getDefaultInstance()) return this;
                if (!other.getErrStr().isEmpty()) {
                    errStr_ = other.errStr_;
                    onChanged();
                }
                if (other.getErrCode() != 0) {
                    setErrCode(other.getErrCode());
                }
                if (!other.getAnsStr().isEmpty()) {
                    ansStr_ = other.ansStr_;
                    onChanged();
                }
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.aiadver.api.asr.grpc.Asr.IatResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.aiadver.api.asr.grpc.Asr.IatResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @return The errStr.
             */
            public java.lang.String getErrStr() {
                java.lang.Object ref = errStr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    errStr_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @param value The errStr to set.
             * @return This builder for chaining.
             */
            public Builder setErrStr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @return The bytes for errStr.
             */
            public com.google.protobuf.ByteString
            getErrStrBytes() {
                java.lang.Object ref = errStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    errStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @param value The bytes for errStr to set.
             * @return This builder for chaining.
             */
            public Builder setErrStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearErrStr() {

                errStr_ = getDefaultInstance().getErrStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             *
             * @return The errCode.
             */
            @java.lang.Override
            public int getErrCode() {
                return errCode_;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             *
             * @param value The errCode to set.
             * @return This builder for chaining.
             */
            public Builder setErrCode(int value) {

                errCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearErrCode() {

                errCode_ = 0;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             *
             * @return The ansStr.
             */
            public java.lang.String getAnsStr() {
                java.lang.Object ref = ansStr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ansStr_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             *
             * @param value The ansStr to set.
             * @return This builder for chaining.
             */
            public Builder setAnsStr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ansStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             *
             * @return The bytes for ansStr.
             */
            public com.google.protobuf.ByteString
            getAnsStrBytes() {
                java.lang.Object ref = ansStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ansStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             *
             * @param value The bytes for ansStr to set.
             * @return This builder for chaining.
             */
            public Builder setAnsStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ansStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 结果
             * </pre>
             *
             * <code>string ansStr = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAnsStr() {

                ansStr_ = getDefaultInstance().getAnsStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 识别结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             *
             * @return The endFlag.
             */
            @java.lang.Override
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 识别结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             *
             * @param value The endFlag to set.
             * @return This builder for chaining.
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 识别结束标记
             * </pre>
             *
             * <code>bool endFlag = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:iat.IatResult)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
