/**
 * Autogenerated by Thrift Compiler (0.13.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.aiadver.api.tts.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-09-29")
public class TTSResult implements org.apache.thrift.TBase<TTSResult, TTSResult._Fields>, java.io.Serializable, Cloneable, Comparable<TTSResult> {
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TTSResult");
    private static final org.apache.thrift.protocol.TField STATUS_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("status_code", org.apache.thrift.protocol.TType.I32, (short) 1);
    private static final org.apache.thrift.protocol.TField SYNTH_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("synthStatus", org.apache.thrift.protocol.TType.I32, (short) 2);
    private static final org.apache.thrift.protocol.TField RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("result", org.apache.thrift.protocol.TType.STRING, (short) 3);
    private static final org.apache.thrift.protocol.TField RESULT_LEN_FIELD_DESC = new org.apache.thrift.protocol.TField("result_len", org.apache.thrift.protocol.TType.I32, (short) 4);
    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TTSResultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TTSResultTupleSchemeFactory();
    // isset id assignments
    private static final int __STATUS_CODE_ISSET_ID = 0;
    private static final int __SYNTHSTATUS_ISSET_ID = 1;
    private static final int __RESULT_LEN_ISSET_ID = 2;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.STATUS_CODE, new org.apache.thrift.meta_data.FieldMetaData("status_code", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.SYNTH_STATUS, new org.apache.thrift.meta_data.FieldMetaData("synthStatus", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.RESULT, new org.apache.thrift.meta_data.FieldMetaData("result", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, true)));
        tmpMap.put(_Fields.RESULT_LEN, new org.apache.thrift.meta_data.FieldMetaData("result_len", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TTSResult.class, metaDataMap);
    }

    public int status_code; // required
    public int synthStatus; // required
    public @org.apache.thrift.annotation.Nullable
    java.nio.ByteBuffer result; // required
    public int result_len; // required
    private byte __isset_bitfield = 0;

    public TTSResult() {
    }

    public TTSResult(
            int status_code,
            int synthStatus,
            java.nio.ByteBuffer result,
            int result_len) {
        this();
        this.status_code = status_code;
        setStatus_codeIsSet(true);
        this.synthStatus = synthStatus;
        setSynthStatusIsSet(true);
        this.result = org.apache.thrift.TBaseHelper.copyBinary(result);
        this.result_len = result_len;
        setResult_lenIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public TTSResult(TTSResult other) {
        __isset_bitfield = other.__isset_bitfield;
        this.status_code = other.status_code;
        this.synthStatus = other.synthStatus;
        if (other.isSetResult()) {
            this.result = org.apache.thrift.TBaseHelper.copyBinary(other.result);
        }
        this.result_len = other.result_len;
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }

    public TTSResult deepCopy() {
        return new TTSResult(this);
    }

    @Override
    public void clear() {
        setStatus_codeIsSet(false);
        this.status_code = 0;
        setSynthStatusIsSet(false);
        this.synthStatus = 0;
        this.result = null;
        setResult_lenIsSet(false);
        this.result_len = 0;
    }

    public int getStatus_code() {
        return this.status_code;
    }

    public TTSResult setStatus_code(int status_code) {
        this.status_code = status_code;
        setStatus_codeIsSet(true);
        return this;
    }

    public void unsetStatus_code() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATUS_CODE_ISSET_ID);
    }

    /**
     * Returns true if field status_code is set (has been assigned a value) and false otherwise
     */
    public boolean isSetStatus_code() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATUS_CODE_ISSET_ID);
    }

    public void setStatus_codeIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATUS_CODE_ISSET_ID, value);
    }

    public int getSynthStatus() {
        return this.synthStatus;
    }

    public TTSResult setSynthStatus(int synthStatus) {
        this.synthStatus = synthStatus;
        setSynthStatusIsSet(true);
        return this;
    }

    public void unsetSynthStatus() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SYNTHSTATUS_ISSET_ID);
    }

    /**
     * Returns true if field synthStatus is set (has been assigned a value) and false otherwise
     */
    public boolean isSetSynthStatus() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SYNTHSTATUS_ISSET_ID);
    }

    public void setSynthStatusIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SYNTHSTATUS_ISSET_ID, value);
    }

    public byte[] getResult() {
        setResult(org.apache.thrift.TBaseHelper.rightSize(result));
        return result == null ? null : result.array();
    }

    public TTSResult setResult(byte[] result) {
        this.result = result == null ? (java.nio.ByteBuffer) null : java.nio.ByteBuffer.wrap(result.clone());
        return this;
    }

    public TTSResult setResult(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer result) {
        this.result = org.apache.thrift.TBaseHelper.copyBinary(result);
        return this;
    }

    public java.nio.ByteBuffer bufferForResult() {
        return org.apache.thrift.TBaseHelper.copyBinary(result);
    }

    public void unsetResult() {
        this.result = null;
    }

    /**
     * Returns true if field result is set (has been assigned a value) and false otherwise
     */
    public boolean isSetResult() {
        return this.result != null;
    }

    public void setResultIsSet(boolean value) {
        if (!value) {
            this.result = null;
        }
    }

    public int getResult_len() {
        return this.result_len;
    }

    public TTSResult setResult_len(int result_len) {
        this.result_len = result_len;
        setResult_lenIsSet(true);
        return this;
    }

    public void unsetResult_len() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RESULT_LEN_ISSET_ID);
    }

    /**
     * Returns true if field result_len is set (has been assigned a value) and false otherwise
     */
    public boolean isSetResult_len() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RESULT_LEN_ISSET_ID);
    }

    public void setResult_lenIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RESULT_LEN_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case STATUS_CODE:
                if (value == null) {
                    unsetStatus_code();
                } else {
                    setStatus_code((java.lang.Integer) value);
                }
                break;

            case SYNTH_STATUS:
                if (value == null) {
                    unsetSynthStatus();
                } else {
                    setSynthStatus((java.lang.Integer) value);
                }
                break;

            case RESULT:
                if (value == null) {
                    unsetResult();
                } else {
                    if (value instanceof byte[]) {
                        setResult((byte[]) value);
                    } else {
                        setResult((java.nio.ByteBuffer) value);
                    }
                }
                break;

            case RESULT_LEN:
                if (value == null) {
                    unsetResult_len();
                } else {
                    setResult_len((java.lang.Integer) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case STATUS_CODE:
                return getStatus_code();

            case SYNTH_STATUS:
                return getSynthStatus();

            case RESULT:
                return getResult();

            case RESULT_LEN:
                return getResult_len();

        }
        throw new java.lang.IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
     */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case STATUS_CODE:
                return isSetStatus_code();
            case SYNTH_STATUS:
                return isSetSynthStatus();
            case RESULT:
                return isSetResult();
            case RESULT_LEN:
                return isSetResult_len();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that == null)
            return false;
        if (that instanceof TTSResult)
            return this.equals((TTSResult) that);
        return false;
    }

    public boolean equals(TTSResult that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_status_code = true;
        boolean that_present_status_code = true;
        if (this_present_status_code || that_present_status_code) {
            if (!(this_present_status_code && that_present_status_code))
                return false;
            if (this.status_code != that.status_code)
                return false;
        }

        boolean this_present_synthStatus = true;
        boolean that_present_synthStatus = true;
        if (this_present_synthStatus || that_present_synthStatus) {
            if (!(this_present_synthStatus && that_present_synthStatus))
                return false;
            if (this.synthStatus != that.synthStatus)
                return false;
        }

        boolean this_present_result = true && this.isSetResult();
        boolean that_present_result = true && that.isSetResult();
        if (this_present_result || that_present_result) {
            if (!(this_present_result && that_present_result))
                return false;
            if (!this.result.equals(that.result))
                return false;
        }

        boolean this_present_result_len = true;
        boolean that_present_result_len = true;
        if (this_present_result_len || that_present_result_len) {
            if (!(this_present_result_len && that_present_result_len))
                return false;
            if (this.result_len != that.result_len)
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + status_code;

        hashCode = hashCode * 8191 + synthStatus;

        hashCode = hashCode * 8191 + ((isSetResult()) ? 131071 : 524287);
        if (isSetResult())
            hashCode = hashCode * 8191 + result.hashCode();

        hashCode = hashCode * 8191 + result_len;

        return hashCode;
    }

    @Override
    public int compareTo(TTSResult other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.valueOf(isSetStatus_code()).compareTo(other.isSetStatus_code());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetStatus_code()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status_code, other.status_code);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.valueOf(isSetSynthStatus()).compareTo(other.isSetSynthStatus());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSynthStatus()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.synthStatus, other.synthStatus);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.valueOf(isSetResult()).compareTo(other.isSetResult());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetResult()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.result, other.result);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.valueOf(isSetResult_len()).compareTo(other.isSetResult_len());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetResult_len()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.result_len, other.result_len);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("TTSResult(");
        boolean first = true;

        sb.append("status_code:");
        sb.append(this.status_code);
        first = false;
        if (!first) sb.append(", ");
        sb.append("synthStatus:");
        sb.append(this.synthStatus);
        first = false;
        if (!first) sb.append(", ");
        sb.append("result:");
        if (this.result == null) {
            sb.append("null");
        } else {
            org.apache.thrift.TBaseHelper.toString(this.result, sb);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("result_len:");
        sb.append(this.result_len);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    /**
     * The set of fields this struct contains, along with convenience methods for finding and manipulating them.
     */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        STATUS_CODE((short) 1, "status_code"),
        SYNTH_STATUS((short) 2, "synthStatus"),
        RESULT((short) 3, "result"),
        RESULT_LEN((short) 4, "result_len");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // STATUS_CODE
                    return STATUS_CODE;
                case 2: // SYNTH_STATUS
                    return SYNTH_STATUS;
                case 3: // RESULT
                    return RESULT;
                case 4: // RESULT_LEN
                    return RESULT_LEN;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    private static class TTSResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public TTSResultStandardScheme getScheme() {
            return new TTSResultStandardScheme();
        }
    }

    private static class TTSResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<TTSResult> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, TTSResult struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // STATUS_CODE
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.status_code = iprot.readI32();
                            struct.setStatus_codeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // SYNTH_STATUS
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.synthStatus = iprot.readI32();
                            struct.setSynthStatusIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // RESULT
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.result = iprot.readBinary();
                            struct.setResultIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // RESULT_LEN
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.result_len = iprot.readI32();
                            struct.setResult_lenIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, TTSResult struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            oprot.writeFieldBegin(STATUS_CODE_FIELD_DESC);
            oprot.writeI32(struct.status_code);
            oprot.writeFieldEnd();
            oprot.writeFieldBegin(SYNTH_STATUS_FIELD_DESC);
            oprot.writeI32(struct.synthStatus);
            oprot.writeFieldEnd();
            if (struct.result != null) {
                oprot.writeFieldBegin(RESULT_FIELD_DESC);
                oprot.writeBinary(struct.result);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(RESULT_LEN_FIELD_DESC);
            oprot.writeI32(struct.result_len);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class TTSResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public TTSResultTupleScheme getScheme() {
            return new TTSResultTupleScheme();
        }
    }

    private static class TTSResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<TTSResult> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, TTSResult struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetStatus_code()) {
                optionals.set(0);
            }
            if (struct.isSetSynthStatus()) {
                optionals.set(1);
            }
            if (struct.isSetResult()) {
                optionals.set(2);
            }
            if (struct.isSetResult_len()) {
                optionals.set(3);
            }
            oprot.writeBitSet(optionals, 4);
            if (struct.isSetStatus_code()) {
                oprot.writeI32(struct.status_code);
            }
            if (struct.isSetSynthStatus()) {
                oprot.writeI32(struct.synthStatus);
            }
            if (struct.isSetResult()) {
                oprot.writeBinary(struct.result);
            }
            if (struct.isSetResult_len()) {
                oprot.writeI32(struct.result_len);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, TTSResult struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(4);
            if (incoming.get(0)) {
                struct.status_code = iprot.readI32();
                struct.setStatus_codeIsSet(true);
            }
            if (incoming.get(1)) {
                struct.synthStatus = iprot.readI32();
                struct.setSynthStatusIsSet(true);
            }
            if (incoming.get(2)) {
                struct.result = iprot.readBinary();
                struct.setResultIsSet(true);
            }
            if (incoming.get(3)) {
                struct.result_len = iprot.readI32();
                struct.setResult_lenIsSet(true);
            }
        }
    }
}

